### ISSUE TITLE
HU13 Creación de clientes

### ISSUE THREAD

**Issue by dejuata** [dejuata/SCR#13]
Descripción HU:

Yo como supervisor, coordinador o auxiliar deseo que el sistema me permita registrar mis clientes. Es decir las empresas y colegios a los que presto mi servicio de transporte.

**Comment by Jose110694** [comment]
Listo desde el tenant se pueden crear los clientes con los campos requeridos.

**Comment by Jose110694** [comment]
Listo desde el tenant se pueden crear los clientes con los campos requeridos.
